config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :articles do
    resources :comments, only: [:create, :destroy, :update]
  end
  devise_for :users
  root 'welcome#index'
end

app/models/article.rb
class Article < ActiveRecord::Base

  belongs_to :user
  has_many :comments

  validates :title, presence: true, uniqueness: true
  validates :body ,presence: true, length:{minimum: 20}
  before_save :set_visits_count


  has_attached_file :cover, styles: { medium:"1280x720", thumb:"800x600"}
  validates_attachment_content_type :cover, :content_type => /\Aimage\/.*\Z/

  def update_visits_count
  self.update(visits_count: self.visits_count + 1)
  end
  private

  def set_visits_count
    self.visits_count ||= 0
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :article
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :articles
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :set_categories
  private
  def set_categories
    @categories = Category.all
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
before_action :authenticate_user!, except: [:show,:index]
before_action :set_article, except: [:index,:new,:create]

#GET /articles
  def index
    @articles = Article.paginate(page: params[:page],per_page:6)
  end

#GET /articles:id
  def show
    @article.update_visits_count
    @comment = Comment.new
    @categories = Category.all
  end

#GET /articles/new
  def new
    @article = Article.new
  end

#POST /articles
  def create
    @article = current_user.articles.new(article_params)
    if @article.save
      redirect_to @article
    else
      render :new
    end
  end

  def destroy

    @article.destroy
    redirect_to articles_path
  end
  def update
    if @article.update(article_params)
      redirect_to @article
    else
      render :edit
    end
  end
  private
def set_article
    @article = Article.find(params[:id])
end

  def article_params
    params.require(:article).permit(:title,:body, :cover)
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :color)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:update, :destroy]
  before_action :set_article
  before_action :authenticate_user!

  def create
    @comment = current_user.comments.new(comment_params)
    @comment.article = @article
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.article, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment.comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment.article, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @article, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def ser_article
      @article = Article.find(params[:article_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_id, :article_id, :body)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<% name ||= "Crear" %>
<h1><% name %> articulo</h1>
<%= form_for(@article) do |f| %>
  <% @article.errors.full_messages.each do |message| %>
<div class="be-red white">
  ** <%= message %> **
</div>
<%end%>
  <div class="field">
    <%= f.text_field :title, placeholder: "Titulo", class:"form-control" %>
  </div>
  <div class="field">
    Portada: <%= f.file_field :cover %>
  </div>
  <div class="field">
    <%= f.text_area :body, placeholder: "Escribe aquí el artículo", style:" height:250px;" , class:"form-control" %>
  </div>
  
  <div class="field">
    <%= f.submit "Guardar", class:"btn be-red white"%>
  </div>
<%end%>

app/views/articles/edit.html.erb
<div style="width:80%;margin:0 auto;">
  <%= render "form", name: "Editar" %>
</div>

app/views/articles/index.html.erb
  <h1>Articulos</h1>
    <%= will_paginate @articlea %>
    <div class="row">
    <% @articles.each do |article| %>
      <div class="col-md-4 top-space">
        <div class="box relative article-height">
          <div class="absolute article-height background-cover" style="background:url(<%=article.cover.url(:thumb) %>); top:0px left0px; width:100%;">

            </div>
          <div class="absolute article-height background-cover" style="background:rgba(0,0,0,0.5); top:0px left0px; width:100%;">

            </div>
            <div class="relative white text-center">
              <h2><%= link_to article.title, article%></h2>
              <p>
              <%=truncate(article.body,length:20) %>
            </p>
            </div>
        </div>


        </div>
      <%end%>
    </div>
  <div class="top-space">

  </div>

app/views/articles/new.html.erb
<div style="width:80%;margin:0 auto;">
  <%= render "form" %>
</div>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<% unless @article.user.nil? %>
<p>
  Escrito por: <%= @article.user.email %>
</p>
<%end%>
<div class="field">
  <%= image_tag @article.cover.url()%>
</div>
<p>
  Visitas: <%= @article.visits_count %>
</p>
<div>
  <%= @article.body %>
</div>
<div class="field">
  <h3>Comentarios</h3>
  <%= render "comments/form" %>
  <ul id="comments-box">

    <% @article.comments.each do |comment| %>
      <li>
        <%= comment.body %>
      </li>
    <%end%>
  </ul>
</div>
<div>
  <%=link_to "Editar", edit_article_path(@article) %>
</div>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.color_field :color %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Color</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.color %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Color:</strong>
  <%= @category.color %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/comments/_form.html.erb
<%= form_for( [@article,@comment], remote: true, html: {id: "comments-form", :"data-type" => "json" }) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<p>
  <strong>Article:</strong>
  <%= @comment.article %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "partials/navigation" %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/partials/_navigation.html.erb
<header>
  <nav class="be-red white large-padding">
    <ul class="no-list row center-xs middle-xs">

      <li class="col-md">
        <%= link_to "Harvin Design & Tecnology", articles_path %>
      </li>
      <li class="col-md">
        <%= link_to "Nuevo", new_article_path %>
      </li>

      <% if user_signed_in?%>
      <li class="col-md">
        <%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete %>
      </li>
      <%else%>
      <li class="col-md">
        <%= link_to "Iniciar sesión", new_user_session_path %>
      </li>
      <li class="col-md">
        <%= link_to "Crear Cuenta", new_user_registration_path %>
      </li>
      <%end%>
    </ul>
  </nav>
</header>

app/views/welcome/index.html.erb
<% if user_signed_in? %>
<h1>Bienvenido <%= current_user.email %></h1>
<%end%>